### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by lantw44** [mdbetancourt/eslint-plugin-nevethrow#1]
I installed the plugin with `npm install --save-dev eslint-plugin-neverthrow`, but ESLint couldn't load it.
```
$ npx eslint .

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-neverthrow". 

(The package "eslint-plugin-neverthrow" was not found when loaded as a Node module from the directory "/path/to/project".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-neverthrow@latest --save-dev  

The plugin "eslint-plugin-neverthrow" was referenced from the config file in ".eslintrc.yaml".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```
```
$ node --use-strict --trace-warnings
Welcome to Node.js v14.18.1.
Type ".help" for more information.
> require('eslint-plugin-neverthrow')
Uncaught:
Error: Cannot find module '/path/to/project/node_modules/eslint-plugin-neverthrow/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/path/to/project/node_modules/eslint-plugin-neverthrow/package.json',
  requestPath: 'eslint-plugin-neverthrow'
}
```

**Comment by supermacro** [comment]
Might the issue simply be that @mdbetancourt has not yet pushed the first version of the plugin to npm?

<img width="993" alt="Screen Shot 2021-11-02 at 1 37 20 PM" src="https://user-images.githubusercontent.com/10621548/139847799-3adf195f-04c0-46d6-9a68-4d711961f3fa.png">

I think a workaround would be to `mv` the built source into `node_modules` just to try it out in a real project. I haven't tried that yet, but might get around to it this week.

**Comment by mdbetancourt** [comment]
sorry actually was a misconfiguration of the package.json, i pushed a new version_
